REM ===========================================================================================
REM
REM  Script:  snapwrap.sql
REM  Author:  Ivan Miles (ipmiles@hotmail.com)
REM  Date:    13-DEC-1999
REM
REM  Desc:    Wrapper script for orasnap script suite 
REM           Basically asks for username, password, connect string, and version as
REM            a) not everyone will want to log on as sys
REM            b) not everyone will want separate icons on their desktop
REM               for each connect string
REM           Also allows choice of scripts to run
REM
REM  Usage:   Icon shortcut should be set to something like:
REM           $ORACLE_HOME\BIN\SQLPLUSW.EXE /nolog @snapwrap
REM           (ex. C:\ORA920\BIN\SQLPLUSW.EXE /nolog @snapwrap)
REM
REM           *** VERY IMPORTANT *** VERY IMPORTANT *** VERY IMPORTANT ***
REM           Modify the "Start In" path, of this shortcut, to reflect 
REM           your OraSnap install (default C:\OraSnap) directory.
REM           *** VERY IMPORTANT *** VERY IMPORTANT *** VERY IMPORTANT ***
REM
REM           
REM  Mods:    13-DEC-1999    Original script
REM           10-JAN-2000    Stewart McGlaughlin (orasnap@hotmail.com)
REM                          Prompting for oracle version
REM                          No longer need separate snap7wrapper and snap8wrapper
REM           20-JAN-2001    Stewart McGlaughlin (orasnap@hotmail.com)
REM                          Add two phase commit
REM           08-JUN-2007    Stewart McGlaughlin (orasnap@hotmail.com)
REM                          Updated with 10g changes
REM
REM ===========================================================================================

clear  screen

set    space         0
set    trimspool     on
set    verify        off
set    heading       off
set    linesize      2000
set    pagesize      0
set    feedback      off
set    long          100000
set    longchunksize 2000
col    text format   a200

undef TOP_USER
undef TOP_PASS
undef ORASID
undef ORAVER

whenever sqlerror exit

prompt
prompt Login failure will cause this script to exit immediately
prompt

accept TOP_USER default sys prompt 'Enter username who has access to DBA views....(SYS): '
accept TOP_PASS             prompt 'Enter password.....................................: ' hide
accept ORASID               prompt 'Enter connect string...............................: '
accept ORAVER   default 9   prompt 'Enter database version (7, 8, 9, 10)............(9): '

prompt
connect &TOP_USER/&TOP_PASS@&ORASID

whenever sqlerror continue

set termout on

prompt
select 'Username...............................................: '||user from dual;
select 'Connected to...........................................: '||name from sys.v_$database;
select 'Database version.......................................: '||&&ORAVER from dual;
prompt
prompt Please select reports to be executed:
accept ALL  default Y prompt 'All............................................(Y): '
accept MINI default Y prompt 'Mini...........................................(Y): '
accept GEN  default N prompt 'General........................................(N): '
accept TS   default N prompt 'Tablespace.....................................(N): '
accept RBS  default N prompt 'Rollback.......................................(N): '
accept USR  default N prompt 'User...........................................(N): '
accept TI   default N prompt 'Tables and Indexes.............................(N): '
accept PART default N prompt 'Partition......................................(N): '
accept OBJ  default N prompt 'Database Objects...............................(N): '
accept HMR  default N prompt 'Hit and Miss Ratio.............................(N): '
accept DEW  default N prompt 'Disk I/O, Events and Waits.....................(N): '
accept FTS  default N prompt 'Full Table Scans...............................(N): '
accept DD   default N prompt 'Data Dictionary................................(N): '
accept CSP  default N prompt 'Cursor and SQL Processing......................(N): '
accept LOCK default N prompt 'Locks..........................................(N): '
accept SESS default N prompt 'Session Statistics.............................(N): '
accept SP   default N prompt 'Shared Pool....................................(N): '
accept REDO default N prompt 'Redo Logs......................................(N): '
accept TPC  default N prompt 'Two Phase Commit...............................(N): '
accept MISC default N prompt 'Miscellaneous..................................(N): '
prompt
prompt

set termout off

spool snapwraprun.sql
select 'REM This script was generated by snapwrap.sql' from dual;
select decode(upper('&&ALL'), 'Y', decode('&&ORAVER',7,'@snap7',    8,'@snap8',    9,'@snap9',    10,'@snap10'))     from dual;
select decode(upper('&&MINI'),'Y', decode('&&ORAVER',7,'@snap7mini',8,'@snap8mini',9,'@snap9mini',10,'@snap10mini')) from dual;
select decode(upper('&&GEN'), 'Y', decode('&&ORAVER',7,'@snap7gen', 8,'@snap8gen', 9,'@snap9gen', 10,'@snap10gen'))  from dual;
select decode(upper('&&TS') , 'Y', decode('&&ORAVER',7,'@snap7ts',  8,'@snap8ts',  9,'@snap9ts',  10,'@snap10ts'))   from dual;
select decode(upper('&&RBS'), 'Y', decode('&&ORAVER',7,'@snap7rbs', 8,'@snap8rbs', 9,'@snap9rbs', 10,'@snap10rbs'))  from dual;
select decode(upper('&&USR'), 'Y', decode('&&ORAVER',7,'@snap7user',8,'@snap8user',9,'@snap9user',10,'@snap10user')) from dual;
select decode(upper('&&TI') , 'Y', decode('&&ORAVER',7,'@snap7ti',  8,'@snap8ti',  9,'@snap9ti',  10,'@snap10ti'))   from dual;
select decode(upper('&&PART'),'Y', decode('&&ORAVER',7,'@snap7part',8,'@snap8part',9,'@snap9part',10,'@snap10part')) from dual;
select decode(upper('&&OBJ'), 'Y', decode('&&ORAVER',7,'@snap7obj', 8,'@snap8obj', 9,'@snap9obj', 10,'@snap10obj'))  from dual;
select decode(upper('&&HMR'), 'Y', decode('&&ORAVER',7,'@snap7hmr', 8,'@snap8hmr', 9,'@snap9hmr', 10,'@snap10hmr'))  from dual;
select decode(upper('&&DEW'), 'Y', decode('&&ORAVER',7,'@snap7dew', 8,'@snap8dew', 9,'@snap9dew', 10,'@snap10dew'))  from dual;
select decode(upper('&&FTS'), 'Y', decode('&&ORAVER',7,'@snap7fts', 8,'@snap8fts', 9,'@snap9fts', 10,'@snap10fts'))  from dual;
select decode(upper('&&DD') , 'Y', decode('&&ORAVER',7,'@snap7dd',  8,'@snap8dd',  9,'@snap9dd',  10,'@snap10dd'))   from dual;
select decode(upper('&&CSP'), 'Y', decode('&&ORAVER',7,'@snap7csp', 8,'@snap8csp', 9,'@snap9csp', 10,'@snap10csp'))  from dual;
select decode(upper('&&LOCK'),'Y', decode('&&ORAVER',7,'@snap7lock',8,'@snap8lock',9,'@snap9lock',10,'@snap10lock')) from dual;
select decode(upper('&&SESS'),'Y', decode('&&ORAVER',7,'@snap7sess',8,'@snap8sess',9,'@snap9sess',10,'@snap10sess')) from dual;
select decode(upper('&&SP'),  'Y', decode('&&ORAVER',7,'@snap7sp',  8,'@snap8sp',  9,'@snap9sp',  10,'@snap10sp'))   from dual;
select decode(upper('&&REDO'),'Y', decode('&&ORAVER',7,'@snap7redo',8,'@snap8redo',9,'@snap9redo',10,'@snap10redo')) from dual;
select decode(upper('&&TPC'), 'Y', decode('&&ORAVER',7,'@snap7tpc', 8,'@snap8tpc', 9,'@snap9tpc', 10,'@snap10tpc'))  from dual;
select decode(upper('&&MISC'),'Y', decode('&&ORAVER',7,'@snap7misc',8,'@snap8misc',9,'@snap9misc',10,'@snap10misc')) from dual;
spool off

@snapwraprun
exit
